2021-05-19 15:21:08,650 INFO    MainThread:1288 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 15:21:08,650 INFO    MainThread:1288 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 15:21:08,651 INFO    MainThread:1288 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_152108-3l8cxe30\logs\debug.log
2021-05-19 15:21:08,652 INFO    MainThread:1288 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_152108-3l8cxe30\logs\debug-internal.log
2021-05-19 15:21:08,654 INFO    MainThread:1288 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D58B80D648>
2021-05-19 15:21:08,657 INFO    MainThread:1288 [wandb_init.py:init():369] calling init triggers
2021-05-19 15:21:08,657 INFO    MainThread:1288 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 15:21:08,657 INFO    MainThread:1288 [wandb_init.py:init():418] starting backend
2021-05-19 15:21:08,658 INFO    MainThread:1288 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-19 15:21:08,663 INFO    MainThread:1288 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 15:21:08,791 INFO    MainThread:1288 [backend.py:ensure_launched():128] started backend process with pid: 19636
2021-05-19 15:21:08,791 INFO    MainThread:1288 [wandb_init.py:init():423] backend started and connected
2021-05-19 15:21:08,791 INFO    MainThread:1288 [wandb_init.py:init():465] updated telemetry
2021-05-19 15:21:08,791 INFO    MainThread:1288 [wandb_init.py:init():484] communicating current version
2021-05-19 15:21:09,725 INFO    MainThread:1288 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-19 15:21:09,740 INFO    MainThread:1288 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 15:21:10,118 INFO    MainThread:1288 [wandb_init.py:init():522] starting run threads in backend
2021-05-19 15:21:10,334 INFO    MainThread:1288 [wandb_run.py:_console_start():1524] atexit reg
2021-05-19 15:21:10,350 INFO    MainThread:1288 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-19 15:21:10,350 INFO    MainThread:1288 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-19 15:21:10,350 INFO    MainThread:1288 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-19 15:21:10,351 INFO    MainThread:1288 [wandb_init.py:init():546] run started, returning control to user process
2021-05-19 15:21:10,351 INFO    MainThread:1288 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 15:21:10,351 INFO    MainThread:1288 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 15:21:10,367 INFO    MainThread:1288 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-19 15:21:12,668 INFO    MainThread:1288 [wandb_watch.py:watch():39] Watching
2021-05-19 15:24:17,139 INFO    MainThread:1288 [wandb_config.py:__setitem__():141] config set save_path = model_save\19_May_202103_24PM_model.pth - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D58B7DB108>>
2021-05-19 15:24:17,139 INFO    MainThread:1288 [wandb_run.py:_config_callback():749] config_cb save_path model_save\19_May_202103_24PM_model.pth None
2021-05-19 15:24:17,318 INFO    MainThread:1288 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 15:24:17,318 INFO    MainThread:1288 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 15:32:09,539 INFO    MainThread:1288 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-19 15:32:09,542 INFO    MainThread:1288 [wandb_run.py:_restore():1466] restore
2021-05-19 15:32:09,805 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 7217
  total_bytes: 7217
}

2021-05-19 15:32:10,351 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 7217
  total_bytes: 10614
}

2021-05-19 15:32:10,673 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:32:10,783 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:32:10,901 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:32:11,011 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:32:11,121 INFO    MainThread:1288 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:32:12,225 INFO    MainThread:1288 [wandb_run.py:_show_summary():1771] rendering summary
2021-05-19 15:32:12,227 INFO    MainThread:1288 [wandb_run.py:_show_history():1809] rendering history
2021-05-19 15:32:12,228 INFO    MainThread:1288 [wandb_run.py:_show_files():1838] logging synced files
