2021-05-19 15:32:27,489 INFO    MainThread:16124 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 15:32:27,489 INFO    MainThread:16124 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 15:32:27,490 INFO    MainThread:16124 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_153227-5g4m6ghd\logs\debug.log
2021-05-19 15:32:27,490 INFO    MainThread:16124 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_153227-5g4m6ghd\logs\debug-internal.log
2021-05-19 15:32:27,492 INFO    MainThread:16124 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000025760AEB588>
2021-05-19 15:32:27,495 INFO    MainThread:16124 [wandb_init.py:init():369] calling init triggers
2021-05-19 15:32:27,495 INFO    MainThread:16124 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 15:32:27,495 INFO    MainThread:16124 [wandb_init.py:init():418] starting backend
2021-05-19 15:32:27,495 INFO    MainThread:16124 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-19 15:32:27,503 INFO    MainThread:16124 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 15:32:27,624 INFO    MainThread:16124 [backend.py:ensure_launched():128] started backend process with pid: 18688
2021-05-19 15:32:27,626 INFO    MainThread:16124 [wandb_init.py:init():423] backend started and connected
2021-05-19 15:32:27,628 INFO    MainThread:16124 [wandb_init.py:init():465] updated telemetry
2021-05-19 15:32:27,628 INFO    MainThread:16124 [wandb_init.py:init():484] communicating current version
2021-05-19 15:32:28,525 INFO    MainThread:16124 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-19 15:32:28,537 INFO    MainThread:16124 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 15:32:28,985 INFO    MainThread:16124 [wandb_init.py:init():522] starting run threads in backend
2021-05-19 15:32:29,158 INFO    MainThread:16124 [wandb_run.py:_console_start():1524] atexit reg
2021-05-19 15:32:29,159 INFO    MainThread:16124 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-19 15:32:29,159 INFO    MainThread:16124 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-19 15:32:29,159 INFO    MainThread:16124 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-19 15:32:29,159 INFO    MainThread:16124 [wandb_init.py:init():546] run started, returning control to user process
2021-05-19 15:32:29,159 INFO    MainThread:16124 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 15:32:29,159 INFO    MainThread:16124 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 15:32:35,728 INFO    MainThread:16124 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-19 15:32:38,099 INFO    MainThread:16124 [wandb_watch.py:watch():39] Watching
2021-05-19 15:35:52,321 INFO    MainThread:16124 [wandb_config.py:__setitem__():141] config set save_path = model_save\19_May_202103_35PM_model.pth - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000025760A899C8>>
2021-05-19 15:35:52,321 INFO    MainThread:16124 [wandb_run.py:_config_callback():749] config_cb save_path model_save\19_May_202103_35PM_model.pth None
2021-05-19 15:35:52,504 INFO    MainThread:16124 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 15:35:52,504 INFO    MainThread:16124 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 15:39:43,363 INFO    MainThread:16124 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-19 15:39:43,364 INFO    MainThread:16124 [wandb_run.py:_restore():1466] restore
2021-05-19 15:39:43,569 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 7217
  total_bytes: 7217
}

2021-05-19 15:39:43,789 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 7217
  total_bytes: 10614
}

2021-05-19 15:39:44,094 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:39:44,199 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:39:44,311 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:39:44,423 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:39:44,535 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:39:44,646 INFO    MainThread:16124 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 10614
  total_bytes: 10614
}

2021-05-19 15:39:45,730 INFO    MainThread:16124 [wandb_run.py:_show_summary():1771] rendering summary
2021-05-19 15:39:45,731 INFO    MainThread:16124 [wandb_run.py:_show_history():1809] rendering history
2021-05-19 15:39:45,732 INFO    MainThread:16124 [wandb_run.py:_show_files():1838] logging synced files
