2021-05-19 11:14:59,348 INFO    MainThread:6580 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 11:14:59,349 INFO    MainThread:6580 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 11:14:59,350 INFO    MainThread:6580 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_111459-1x3vnhq9\logs\debug.log
2021-05-19 11:14:59,350 INFO    MainThread:6580 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_111459-1x3vnhq9\logs\debug-internal.log
2021-05-19 11:14:59,351 INFO    MainThread:6580 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000019490E07548>
2021-05-19 11:14:59,354 INFO    MainThread:6580 [wandb_init.py:init():369] calling init triggers
2021-05-19 11:14:59,354 INFO    MainThread:6580 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 11:14:59,355 INFO    MainThread:6580 [wandb_init.py:init():418] starting backend
2021-05-19 11:14:59,355 INFO    MainThread:6580 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-19 11:14:59,363 INFO    MainThread:6580 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 11:14:59,487 INFO    MainThread:6580 [backend.py:ensure_launched():128] started backend process with pid: 14888
2021-05-19 11:14:59,488 INFO    MainThread:6580 [wandb_init.py:init():423] backend started and connected
2021-05-19 11:14:59,490 INFO    MainThread:6580 [wandb_init.py:init():465] updated telemetry
2021-05-19 11:14:59,490 INFO    MainThread:6580 [wandb_init.py:init():484] communicating current version
2021-05-19 11:15:00,389 INFO    MainThread:6580 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-19 11:15:00,391 INFO    MainThread:6580 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 11:15:00,774 INFO    MainThread:6580 [wandb_init.py:init():522] starting run threads in backend
2021-05-19 11:15:01,096 INFO    MainThread:6580 [wandb_run.py:_console_start():1524] atexit reg
2021-05-19 11:15:01,096 INFO    MainThread:6580 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-19 11:15:01,097 INFO    MainThread:6580 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-19 11:15:01,097 INFO    MainThread:6580 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-19 11:15:01,097 INFO    MainThread:6580 [wandb_init.py:init():546] run started, returning control to user process
2021-05-19 11:15:01,097 INFO    MainThread:6580 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 11:15:01,098 INFO    MainThread:6580 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 11:15:04,679 INFO    MainThread:6580 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-19 11:15:07,066 INFO    MainThread:6580 [wandb_watch.py:watch():39] Watching
2021-05-19 11:23:27,166 INFO    MainThread:6580 [wandb_config.py:__setitem__():141] config set save_path = model_save\19_May_202111_23AM_model.pth - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001948BEEC988>>
2021-05-19 11:23:27,166 INFO    MainThread:6580 [wandb_run.py:_config_callback():749] config_cb save_path model_save\19_May_202111_23AM_model.pth None
2021-05-19 11:23:44,766 INFO    MainThread:6580 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 11:23:44,767 INFO    MainThread:6580 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 11:24:37,373 INFO    MainThread:6580 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-19 11:24:37,374 INFO    MainThread:6580 [wandb_run.py:_restore():1466] restore
2021-05-19 11:24:37,727 INFO    MainThread:6580 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6321532
  total_bytes: 6321532
}

2021-05-19 11:24:38,081 INFO    MainThread:6580 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6321532
  total_bytes: 6504275
}

2021-05-19 11:24:38,812 INFO    MainThread:6580 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6504275
  total_bytes: 6504275
}

2021-05-19 11:24:38,925 INFO    MainThread:6580 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6504275
  total_bytes: 6504275
}

2021-05-19 11:24:40,068 INFO    MainThread:6580 [wandb_run.py:_show_summary():1771] rendering summary
2021-05-19 11:24:40,069 INFO    MainThread:6580 [wandb_run.py:_show_history():1809] rendering history
2021-05-19 11:24:40,071 INFO    MainThread:6580 [wandb_run.py:_show_files():1838] logging synced files
