2021-05-19 10:35:08,333 INFO    MainThread:20808 [wandb_setup.py:_flush():69] setting env: {}
2021-05-19 10:35:08,334 INFO    MainThread:20808 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-19 10:35:08,334 INFO    MainThread:20808 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_103508-2l9zo343\logs\debug.log
2021-05-19 10:35:08,335 INFO    MainThread:20808 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\Lorenzo\PycharmProjects\flow-forecast\notebooks\wandb\run-20210519_103508-2l9zo343\logs\debug-internal.log
2021-05-19 10:35:08,336 INFO    MainThread:20808 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000249A8D0F988>
2021-05-19 10:35:08,338 INFO    MainThread:20808 [wandb_init.py:init():369] calling init triggers
2021-05-19 10:35:08,338 INFO    MainThread:20808 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-19 10:35:08,338 INFO    MainThread:20808 [wandb_init.py:init():418] starting backend
2021-05-19 10:35:08,339 INFO    MainThread:20808 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-19 10:35:08,346 INFO    MainThread:20808 [backend.py:ensure_launched():123] starting backend process...
2021-05-19 10:35:08,456 INFO    MainThread:20808 [backend.py:ensure_launched():128] started backend process with pid: 19364
2021-05-19 10:35:08,457 INFO    MainThread:20808 [wandb_init.py:init():423] backend started and connected
2021-05-19 10:35:08,459 INFO    MainThread:20808 [wandb_init.py:init():465] updated telemetry
2021-05-19 10:35:08,460 INFO    MainThread:20808 [wandb_init.py:init():484] communicating current version
2021-05-19 10:35:09,549 INFO    MainThread:20808 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.30 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-19 10:35:09,553 INFO    MainThread:20808 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-19 10:35:10,030 INFO    MainThread:20808 [wandb_init.py:init():522] starting run threads in backend
2021-05-19 10:35:10,259 INFO    MainThread:20808 [wandb_run.py:_console_start():1524] atexit reg
2021-05-19 10:35:10,259 INFO    MainThread:20808 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.WRAP
2021-05-19 10:35:10,260 INFO    MainThread:20808 [wandb_run.py:_redirect():1414] Wrapping output streams.
2021-05-19 10:35:10,260 INFO    MainThread:20808 [wandb_run.py:_redirect():1438] Redirects installed.
2021-05-19 10:35:10,260 INFO    MainThread:20808 [wandb_init.py:init():546] run started, returning control to user process
2021-05-19 10:35:10,260 INFO    MainThread:20808 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 10:35:10,260 INFO    MainThread:20808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 10:35:10,272 INFO    MainThread:20808 [wandb_init.py:_resume_backend():258] resuming backend
2021-05-19 10:35:12,680 INFO    MainThread:20808 [wandb_watch.py:watch():39] Watching
2021-05-19 10:43:36,614 INFO    MainThread:20808 [wandb_config.py:__setitem__():141] config set save_path = model_save\19_May_202110_43AM_model.pth - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000249A8D0F308>>
2021-05-19 10:43:36,614 INFO    MainThread:20808 [wandb_run.py:_config_callback():749] config_cb save_path model_save\19_May_202110_43AM_model.pth None
2021-05-19 10:43:54,845 INFO    MainThread:20808 [wandb_init.py:_pause_backend():249] pausing backend
2021-05-19 10:43:54,845 INFO    MainThread:20808 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-19 11:14:46,511 INFO    MainThread:20808 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 0
2021-05-19 11:14:46,512 INFO    MainThread:20808 [wandb_run.py:_restore():1466] restore
2021-05-19 11:14:46,799 INFO    MainThread:20808 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6324660
  total_bytes: 6324660
}

2021-05-19 11:14:47,218 INFO    MainThread:20808 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6324660
  total_bytes: 6506089
}

2021-05-19 11:14:48,120 INFO    MainThread:20808 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 5
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6506089
  total_bytes: 6506089
}

2021-05-19 11:14:48,236 INFO    MainThread:20808 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 95
}
pusher_stats {
  uploaded_bytes: 6506089
  total_bytes: 6506089
}

2021-05-19 11:14:49,390 INFO    MainThread:20808 [wandb_run.py:_show_summary():1771] rendering summary
2021-05-19 11:14:49,391 INFO    MainThread:20808 [wandb_run.py:_show_history():1809] rendering history
2021-05-19 11:14:49,392 INFO    MainThread:20808 [wandb_run.py:_show_files():1838] logging synced files
